import Head from 'next/head';
//import Image from 'next/image';
import Header from './header';
import styles from '../styles/Home.module.css';

export default function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anh Tuan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Nguyễn Anh Tuấn</h1>
        <Header />
      </main>
    </div>
  );
}
