import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Home from './home';
import styles from '../styles/Home.module.css';

export default function App() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anh Tuan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Link href="/home">
          <a>Trang chủ</a>
        </Link>
      </header>

      <main className={styles.main}>
        <h1>Nguyễn Anh Tuấn</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
